### ISSUE TITLE
AttributeError: python: undefined symbol: archive_errno

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/python-libarchive-c-feedstock#13]
Issue:

When I try to use this package in a Debian-based Docker container, I get the following error:

```
$ python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/opt/conda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/opt/conda/lib/python3.6/site-packages/libarchive/ffi.py", line 108, in <module>
    errno = ffi('errno', [c_archive_p], c_int)
  File "/opt/conda/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: archive_errno
```

This same error was previously reported as a [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840482#10).

Not suprisingly, installing diffoscope from conda-forge (which depends python-libarchive-c) does not change anything. However, surprisingly, installing diffoscope with APT fixes the error. Thus there must be something that APT is installing that this recipe depends on.

Here's a Dockerfile to reproduce the above description:

```
FROM continuumio/miniconda3:latest
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840482

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git

RUN conda config --add channels defaults && \
    conda config --add channels conda-forge

RUN conda config \
  --set always_yes yes \
  --set changeps1 no

RUN git clone https://github.com/conda-forge/python-libarchive-c-feedstock.git

WORKDIR python-libarchive-c-feedstock/recipe

RUN conda install python-libarchive-c

# https://github.com/conda-forge/python-libarchive-c-feedstock/blob/master/recipe/meta.yaml#L37
ENV TEST "import libarchive; libarchive.extract_file('test/hello_world.xar')"

RUN python -c "$TEST" ; exit 0

RUN conda install diffoscope

RUN python -c "$TEST" ; exit 0

RUN apt-get install -y --no-install-recommends diffoscope

RUN python -c "$TEST" ; exit 0

CMD [ "/bin/bash" ]
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py36_1003    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
conda                     4.5.11                py36_1000    conda-forge
conda-env                 2.6.0                         1  
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
diffoscope                106                        py_0    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
idna                      2.7                   py36_1002    conda-forge
libarchive                3.3.3                h823be47_0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libiconv                  1.15                 h470a237_3    conda-forge
libmagic                  5.33                 h470a237_0    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
ncurses                   6.1                  hf484d3e_0  
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-libarchive-c       2.8                   py36_1004    conda-forge
python-magic              0.4.15                   py36_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.20.1                py36_1000    conda-forge
ruamel_yaml               0.15.71          py36h470a237_0    conda-forge
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.24.0               h84994c4_0  
tk                        8.6.8                hbc83047_0  
urllib3                   1.23                  py36_1001    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               ha838bed_2  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.1 CPython/3.6.6 Linux/4.15.0-39-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False


```
</details>

**Comment by kyleabeauchamp** [comment]
I think I've observed this issue as well.

**Comment by mingwandroid** [comment]
> libarchive                3.3.3                h823be47_0    conda-forge

This indicates libarchive hasn't been rebuild with the new compilers I think?

**Comment by tecty** [comment]
I have observed same issue while compiling sel4 on tutorial interrupts in an ubuntu container.

**Comment by jakirkham** [comment]
@tecty , can you please file a new issue? Based on Ray’s comment this should already have been resolved quite some time ago.

**Comment by tecty** [comment]
> @tecty , can you please file a new issue? Based on Ray’s comment this should already have been resolved quite some time ago.

Just a hidden dependency on libarchive c I didn't install. I fixed it.
