### ISSUE TITLE
Windows Python 2.7 CI build failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-libarchive-c-feedstock#8]
This [Python 2.7 build on Windows is failing]( https://ci.appveyor.com/project/conda-forge/python-libarchive-c-feedstock/builds/19370059/job/y8kfln29np8fu5s5 ). Snippet of the traceback below. Looks very similar to issue ( https://github.com/conda/conda-build/issues/2959 ). All other details can be found in the log linked above.

```python
Traceback (most recent call last):
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\commands\install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\operations\prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\download.py", line 823, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\site-packages\pip\_internal\download.py", line 699, in unpack_file_url
    shutil.copytree(link_path, location, symlinks=True)
  File "C:\bld\python-libarchive-c_1539094373987\_h_env\lib\shutil.py", line 222, in copytree
    raise Error, errors
Error: [('C:\\bld\\python-libarchive-c_1539094373987\\work\\tests\\data\\????.README', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-c8wcjc\\tests\\data\\????.README', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\python-libarchive-c_1539094373987\\\\work\\\\tests\\\\data\\\\????.README'"), ('C:\\bld\\python-libarchive-c_1539094373987\\work\\tests\\data\\????.zip', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-c8wcjc\\tests\\data\\????.zip', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\python-libarchive-c_1539094373987\\\\work\\\\tests\\\\data\\\\????.zip'"), ('C:\\bld\\python-libarchive-c_1539094373987\\work\\tests\\data\\????.zip.json', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-c8wcjc\\tests\\data\\????.zip.json', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\python-libarchive-c_1539094373987\\\\work\\\\tests\\\\data\\\\????.zip.json'")]
```

**Comment by jakirkham** [comment]
cc @marscher

**Comment by jakirkham** [comment]
Good news: PR ( https://github.com/conda-forge/python-libarchive-c-feedstock/pull/10 ) fixes this.
Bad news: It switches to `setuptools` instead of `pip`.

Seems like a reasonable path to get packages built. Though if others want to find a way to get this to work with `pip` that would be welcome as well.

**Comment by mingwandroid** [comment]
> Bad news: It switches to setuptools instead of pip.

In what way is this bad?
